-----------------------------------------------------------------------------------------------------------------------------------------
-- PRODUCTS
-----------------------------------------------------------------------------------------------------------------------------------------
Products = {
	["Cemitery"] = {
		["Timer"] = 10,
		["Police"] = true,
		["Animation"] = {
			["Dict"] = "amb@medic@standing@tendtodead@idle_a",
			["Anim"] = "idle_a"
		},
		["Itens"] = {
			{ ["Item"] = "joint", ["Chance"] = 25, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "cocaine", ["Chance"] = 25, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "meth", ["Chance"] = 25, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "alliance", ["Chance"] = 50, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "scotchtape", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "insulatingtape", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "screws", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 3 },
			{ ["Item"] = "screwnuts", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 3 },
			{ ["Item"] = "goldnecklace", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "silverchain", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "horsefigurine", ["Chance"] = 3, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "toothpaste", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "treasurebox", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "suitcase", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "gauze", ["Chance"] = 45, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "lockpick", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "celular", ["Chance"] = 45, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "cigarette", ["Chance"] = 75, ["Min"] = 4, ["Max"] = 6 },
			{ ["Item"] = "lighter", ["Chance"] = 45, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "vape", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "pager", ["Chance"] = 2, ["Min"] = 1, ["Max"] = 1 }
		},
		["Residual"] = "Resíduo de Clorofórmio"
	}
	
}
-----------------------------------------------------------------------------------------------------------------------------------------
-- TRASHITENS
-----------------------------------------------------------------------------------------------------------------------------------------
TrashItens = {
	{ ["Item"] = "plastic", ["Chance"] = 100, ["Min"] = 6, ["Max"] = 10, ["Addition"] = 0.075 },
	{ ["Item"] = "glass", ["Chance"] = 100, ["Min"] = 6, ["Max"] = 10, ["Addition"] = 0.075 },
	{ ["Item"] = "rubber", ["Chance"] = 100, ["Min"] = 6, ["Max"] = 10, ["Addition"] = 0.075 },
	{ ["Item"] = "aluminum", ["Chance"] = 50, ["Min"] = 4, ["Max"] = 8, ["Addition"] = 0.025 },
	{ ["Item"] = "copper", ["Chance"] = 50, ["Min"] = 4, ["Max"] = 8, ["Addition"] = 0.025 },
	{ ["Item"] = "techtrash", ["Chance"] = 5, ["Min"] = 1, ["Max"] = 2, ["Addition"] = 0.0 },
	{ ["Item"] = "tarp", ["Chance"] = 7, ["Min"] = 1, ["Max"] = 2, ["Addition"] = 0.0 },
	{ ["Item"] = "sheetmetal", ["Chance"] = 5, ["Min"] = 1, ["Max"] = 2, ["Addition"] = 0.0 },
	{ ["Item"] = "roadsigns", ["Chance"] = 5, ["Min"] = 1, ["Max"] = 2, ["Addition"] = 0.0 },
	{ ["Item"] = "scotchtape", ["Chance"] = 3, ["Min"] = 1, ["Max"] = 2, ["Addition"] = 0.0 },
	{ ["Item"] = "insulatingtape", ["Chance"] = 3, ["Min"] = 1, ["Max"] = 2, ["Addition"] = 0.0 },
	{ ["Item"] = "electroniccomponents", ["Chance"] = 3, ["Min"] = 1, ["Max"] = 2, ["Addition"] = 0.0 },
	{ ["Item"] = "batteryaa", ["Chance"] = 5, ["Min"] = 1, ["Max"] = 2, ["Addition"] = 0.0 },
	{ ["Item"] = "batteryaaplus", ["Chance"] = 5, ["Min"] = 1, ["Max"] = 2, ["Addition"] = 0.0 },
	{ ["Item"] = "emptybottle", ["Chance"] = 25, ["Min"] = 3, ["Max"] = 4, ["Addition"] = 0.0 }
}
-----------------------------------------------------------------------------------------------------------------------------------------
-- LOOTS
-----------------------------------------------------------------------------------------------------------------------------------------
Loots = {
	["LootMedics"] = {
		["Players"] = {},
		["Cooldown"] = 600,
		["Item"] = "medicalkey",
		["List"] = {
			{ ["Item"] = "joint", ["Chance"] = 65, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "cocaine", ["Chance"] = 65, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "meth", ["Chance"] = 65, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "crack", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "heroin", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "metadone", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "codeine", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "amphetamine", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "sulfuric", ["Chance"] = 45, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "acetone", ["Chance"] = 45, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "saline", ["Chance"] = 45, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "alcohol", ["Chance"] = 45, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "syringe01", ["Chance"] = 65, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "syringe02", ["Chance"] = 65, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "syringe03", ["Chance"] = 65, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "syringe04", ["Chance"] = 65, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "bandage", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "medkit", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "ritmoneury", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "sinkalmy", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "analgesic", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "gauze", ["Chance"] = 45, ["Min"] = 2, ["Max"] = 4 },
			{ ["Item"] = "adrenaline", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_rubber", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_saline", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_acetone", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_alcohol", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_gauze", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_medkit", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_analgesic", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_sinkalmy", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_bandage", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ritmoneury", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_sulfuric", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 }
		}
	},
	["LootWeapons"] = {
		["Players"] = {},
		["Cooldown"] = 7200,
		["Item"] = "weaponkey",
		["List"] = {
			{ ["Item"] = "repairkit01", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "repairkit02", ["Chance"] = 10, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "repairkit03", ["Chance"] = 5, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "repairkit04", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "nitro", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "circuit", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "gunpowder", ["Chance"] = 65, ["Min"] = 1, ["Max"] = 3 },
			{ ["Item"] = "pistolbody", ["Chance"] = 50, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "smgbody", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "riflebody", ["Chance"] = 20, ["Min"] = 3, ["Max"] = 8 },
			{ ["Item"] = "techtrash", ["Chance"] = 50, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "explosives", ["Chance"] = 50, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "safependrive", ["Chance"] = 5, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "weaponparts", ["Chance"] = 15, ["Min"] = 2, ["Max"] = 3 },
			{ ["Item"] = "dismantle", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blocksignal", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "ballisticplate", ["Chance"] = 10, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "lockpick", ["Chance"] = 50, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "handcuff", ["Chance"] = 15, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "hood", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_GRIP", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_PISTOL_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_MUSKET", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_MAGAZINE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_weaponparts", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_MUSKET_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_smgbody", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_HEAVYPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_FLASHLIGHT", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_riflebody", ["Chance"] = 1, ["Min"] = 3, ["Max"] = 8 },
			{ ["Item"] = "blueprint_WEAPON_PISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SNSPISTOL_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_SILENCER", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_PISTOL50", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_STUNGUN", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SNSPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_gunpowder", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_pistolbody", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_CROSSHAIR", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_PISTOL_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SMOKEGRENADE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_MOLOTOV", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SHOTGUN_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_RIFLE_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SMG_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_COMBATPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_VINTAGEPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 }
		}
	},
	["LootSupplies"] = {
		["Players"] = {},
		["Cooldown"] = 600,
		["Item"] = "utilkey",
		["List"] = {
			{ ["Item"] = "weedclone", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "cokeclone", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "plate", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "plastic", ["Chance"] = 100, ["Min"] = 6, ["Max"] = 10 },
			{ ["Item"] = "glass", ["Chance"] = 100, ["Min"] = 6, ["Max"] = 10 },
			{ ["Item"] = "rubber", ["Chance"] = 100, ["Min"] = 6, ["Max"] = 10 },
			{ ["Item"] = "aluminum", ["Chance"] = 75, ["Min"] = 4, ["Max"] = 8 },
			{ ["Item"] = "copper", ["Chance"] = 75, ["Min"] = 4, ["Max"] = 8 },
			{ ["Item"] = "techtrash", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "tarp", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "sheetmetal", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "roadsigns", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "explosives", ["Chance"] = 45, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "scotchtape", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "insulatingtape", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "screws", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "screwnuts", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 2 },
			{ ["Item"] = "boilies", ["Chance"] = 75, ["Min"] = 5, ["Max"] = 10 },
			{ ["Item"] = "sapphire_pure", ["Chance"] = 50, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "emerald_pure", ["Chance"] = 50, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "ruby_pure", ["Chance"] = 50, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "gold_pure", ["Chance"] = 50, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "iron_pure", ["Chance"] = 50, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "lead_pure", ["Chance"] = 50, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "tin_pure", ["Chance"] = 50, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "diamond_pure", ["Chance"] = 50, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "copper_pure", ["Chance"] = 50, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "binoculars", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "camera", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "postit", ["Chance"] = 65, ["Min"] = 4, ["Max"] = 6 },
			{ ["Item"] = "radio", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "cigarette", ["Chance"] = 75, ["Min"] = 3, ["Max"] = 6 },
			{ ["Item"] = "lighter", ["Chance"] = 25, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "soap", ["Chance"] = 35, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "emptybottle", ["Chance"] = 75, ["Min"] = 3, ["Max"] = 4 },
			{ ["Item"] = "blueprint_batteryaaplus", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_rubber", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_silverchain", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_glass", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_electroniccomponents", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_toothpaste", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_videocard", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_screws", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_roadsigns", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_processorfan", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_rammemory", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_copper", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_powercable", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_batteryaa", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_processor", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_insulatingtape", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_safependrive", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_aluminum", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_plastic", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_techtrash", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_scotchtape", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_screwnuts", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_sheetmetal", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_powersupply", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ssddrive", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_goldnecklace", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_tarp", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_circuit", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_horsefigurine", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_explosives", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 }
		}
	},
	["LootLegendary"] = {
		["Players"] = {},
		["Cooldown"] = 10800,
		["Item"] = "legendarykey",
		["List"] = {
			{ ["Item"] = "blueprint_WEAPON_ADVANCEDRIFLE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_COMPACTRIFLE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_batteryaaplus", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_rubber", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_silverchain", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_GRIP", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SAWNOFFSHOTGUN", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_saline", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_glass", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_MICROSMG", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_HEAVYRIFLE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_PISTOL_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_acetone", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_ASSAULTRIFLE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_alcohol", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_electroniccomponents", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_gauze", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_MUSKET", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_BULLPUPRIFLE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_toothpaste", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_MAGAZINE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_videocard", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_screws", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_ASSAULTRIFLE_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_roadsigns", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_processorfan", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_rammemory", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_weaponparts", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_MUSKET_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_copper", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_smgbody", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_HEAVYPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_medkit", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_powercable", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_batteryaa", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_CARBINERIFLE_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_FLASHLIGHT", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_processor", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_insulatingtape", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_safependrive", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_riflebody", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_PISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_aluminum", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SNSPISTOL_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_SILENCER", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SPECIALCARBINE_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_plastic", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_PISTOL50", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_MINISMG", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_TACTICALRIFLE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_techtrash", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_scotchtape", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_STUNGUN", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_screwnuts", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SNSPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_analgesic", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_sinkalmy", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_gunpowder", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_bandage", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_GUSENBERG", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_ASSAULTSMG", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SMG_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_pistolbody", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_sheetmetal", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SMG", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_powersupply", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_PUMPSHOTGUN_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_PUMPSHOTGUN", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SPECIALCARBINE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_BULLPUPRIFLE_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_CARBINERIFLE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ATTACH_CROSSHAIR", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_MACHINEPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_APPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_PISTOL_MK2", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SMOKEGRENADE", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_MOLOTOV", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SHOTGUN_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_RIFLE_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_SMG_AMMO", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_COMBATPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ssddrive", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_goldnecklace", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_WEAPON_VINTAGEPISTOL", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_explosives", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_tarp", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_ritmoneury", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_sulfuric", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_circuit", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 },
			{ ["Item"] = "blueprint_horsefigurine", ["Chance"] = 1, ["Min"] = 1, ["Max"] = 1 }
		}
	},
	["LootCode"] = {
		["Players"] = {},
		["Code"] = "5221",
		["Cooldown"] = 600,
		["List"] = {
			{ ["Item"] = "bandage", ["Chance"] = 100, ["Min"] = 1, ["Max"] = 1 }
		}
	}
}